language: java
notifications:
  email: false
before_install:
  # download the latest android sdk and unzip
  - wget http://dl.google.com/android/android-sdk_r20.0.3-linux.tgz
  - tar -zxf android-sdk_r20.0.3-linux.tgz
  # setup your ANDROID_HOME and PATH environment variables
  # use ~/builds/[Github username]/[project]/android-sdk-linux
  - export ANDROID_HOME=~/builds/eyeem/EYeEm-Java-SDK/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # only update the sdk for the tools and platform-tools (1,2) and whatever api level
  # you are building for android (run "android list sdk" to get the full list. 9 = 2.3.3 or API level 10
  - android update sdk --obsolete --filter 16,15,14,13,12,11,10,9,8,7,6,1,2,3,4 --no-ui --force